<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Lead extends Model
{
    protected $fillable = [
        'user_id',
        'team_id',
        'lead_number',
        'owner_occupy',
        'occupancy_status',
        'firstname',
        'middlename',
        'lastname',
        'phone',
        'phone2',
        'phone3',
        'phone4',
        'phone5',
        'martial_status',
        'spouce',
        'language',
        'state',
        'city',
        'street',
        'zipcode',
        'property_classification',
        'property_type',
        'multi_family',
        'construction_type',
        'year_built',
        'building_size',
        'bedroom',
        'bathroom',
        'lot_size',
        'home_feature',
        'num_of_stories',
        'association_fee',
        'reason_to_sale',
        'picture',
        'lead_condition',
        'lead_source',
        'asking_price',
        'arv',
        'assignment_fee',
        'rehab_cost',
        'arv_rehab_cost',
        'arv_sales_closingcost',
        'property_total_value',
        'wholesales_closing_cost',
        'all_in_cost',
        'investor_profit',
        'sales_price',
        'maximum_allow_offer',
        'offer_range_low',
        'offer_range_high',
        'appointment_time',
        'split',
        'email',
        'company',
        'note',
        'lead_type',
        'lead_status',
        'confirmation_reason',
        'cancellation_reason',
        'is_duplicated',
        'lead_date',
        'confirmed_by',
        'confirmation_times',
        'contract_amount',
        'created_at',
        'updated_at',
        'deleted_at',
    ];
}